export const RETRIVE_USER = 'RETRIVE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const COPY_USER = 'COPY_USER'
export const TURN_ON = 'TURN_ON'
export const TURN_OFF = 'TURN_OFF'

export const RECEIVE_USERS = 'RECEIVE_USERS'
export const RECEIVE_PURE_USERS = 'RECEIVE_PURE_USERS'
export const RECEIVE_USERS_SIZE = 'RECEIVE_USERS_SIZE'


export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const COPY_USER_REQUEST = "COPY_USER_REQUEST"
export const COPY_USER_SUCCESS = "COPY_USER_SUCCESS"
export const COPY_USER_FAILURE = "COPY_USER_FAILURE"

export const TURNON_USER_REQUEST = "TURNON_USER_REQUEST"
export const TURNON_USER_SUCCESS = "TURNON_USER_SUCCESS"
export const TURNON_USER_FAILURE = "TURNON_USER_FAILURE"

export const CURRENT_UPDATE_USER = "CURRENT_UPDATE_USER"

export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE"

export const GET_ALL_HOS = "GET_ALL_HOS"
export const GET_SOME_DEPARTS = "GET_SOME_DEPARTS"
export const GET_ALL_GROUPS = "GET_ALL_GROUPS"

export const SEARCH_RESULT = "SEARCH_RESULT"

export const GET_ALL_KS = " GET_ALL_KS"

export const GET_CURRENT_USER = "GET_CURRENT_USER"

export const RECEIVE_SEARCH_USER = 'RECEIVE_SEARCH_USER'

export const ADMIN_LIMIT = 'ADMIN_LIMIT'

export const DRILL_HOS = 'DRILL_HOS'
